on: [push, pull_request]
name: makefile

jobs:
  make:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install Protoc
        uses: arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3 # v1.1.2

      - uses: actions/setup-go@v2
        with:
          go-version: "1.19.x"
      - name: Check that go.mod is tidy
        run: |
          cd golang
          go mod tidy
          if [[ -n $(git ls-files --other --exclude-standard --directory -- go.sum) ]]; then
            echo "go.sum was added by go mod tidy"
            exit 1
          fi
          git diff --exit-code -- go.sum go.mod
      - name: Make
        run: make
